### ISSUE TITLE
ERROR: failed verifying credentials: incorrect username or password

### ISSUE THREAD

**Issue by 27Bslash6** [aquasecurity/microscanner#19]
This error repeatedly, randomly reappears, despite the token known to be good.

See: https://circleci.com/gh/greenpeace/planet4-docker/3313

Is this a known issue that has a timeline to be fixed?

Are these recurrent downtimes due to upgrades of the service or some other failure?

**Comment by lizrice** [comment]
Apparently this is likely because the token had reached the usage limit for the day. But we should really have a different error code for that.
