### ISSUE TITLE
Scanning for application level packages

### ISSUE THREAD

**Issue by Avni-Sharma** [aquasecurity/microscanner#22]
I saw that the microscanner has support for OS level packages. Does it also have support for application level packages. For example flask is a package for pypi ecosystem. So does it scan for this as well, or is there a future possibility to do the same.

**Comment by elsmorian** [comment]
@Avni-Sharma I believe it does not but I could well be wrong, I'm not a part of this project, just a user! We currently use Safety ( https://pyup.io/safety/ ) for testing our Python packages though I will admit our testing pipeline needs a bit of work so there may be better options out there!
