### ISSUE TITLE
Improved one-liner for Docker builds

### ISSUE THREAD

**Issue by steven166** [aquasecurity/microscanner#3]
Hi,
First of all, I like this tool very much: simple, fast and it does what it needs to be doing.

The following oneliner will install, run and cleanup everything in the same layer of a Docker build, so that it will not add any storage size to the final image.
```
RUN apk add --no-cache ca-certificates && update-ca-certificates && \
    wget -O /microscanner https://get.aquasec.com/microscanner && \
    chmod +x /microscanner && \
    /microscanner <token> && \
    rm -rf /microscanner
```

**Comment by lizrice** [comment]
Good idea - I have added it to the readme. Thank you!
