### ISSUE TITLE
Is the token still open for register?

### ISSUE THREAD

**Issue by pierrchen** [aquasecurity/microscanner#46]
Hi,
I tried both requesting the token from the website and running the docker per instruction but wasn't able to get the token after waiting more than 12 hours.

Is the token still open for register?

**Comment by jerbia** [comment]
Hi @pierrchen.
There was a problem with emails being classified as SPAM. We changed the sender and it seems to work now. Can you try again?

**Comment by jerbia** [comment]
Issue fixed.
