### ISSUE TITLE
Never receiving a token

### ISSUE THREAD

**Issue by bitsofinfo** [aquasecurity/microscanner#48]
I'm tried multiple emails, never get a token to try using this....

**Comment by jerbia** [comment]
Hi @bitsofinfo. There was a problem with emails from info@aquasec.com getting into SPAM.
We changed the sender and it seems to work now.
Can you try again?

**Comment by jerbia** [comment]
There was an issue with email getting into SPAM. Should be fixed now. Closing the issue.
