### ISSUE TITLE
Unable to receive token

### ISSUE THREAD

**Issue by hbl-cuongvv** [aquasecurity/microscanner#58]
Hi,
I'm trying to register for a token with gmail, but cannot succeed. I tried both way that mentioned at https://github.com/aquasecurity/microscanner#registering-for-a-token
Can anyone help me please

**Comment by lizrice** [comment]
No new tokens are being issued because [Microscanner is now deprecated in favour of Trivy](https://github.com/aquasecurity/microscanner#microscanner-is-now-deprecated-in-favour-of-trivy). I'll modify the readme about issuing tokens to make that clearer
